rule = [
  { key = "aldi",              category = "Jedlo/potraviny" },
  { key = "lidl",              category = "Jedlo/potraviny" },
  { key = "netto",             category = "Jedlo/potraviny" },
  { key = "kaufland",          category = "Jedlo/potraviny" },
  { key = "edeka",             category = "Jedlo/potraviny" },
  { key = "rewe",              category = "Jedlo/potraviny" },
  { key = "penny",             category = "Jedlo/potraviny" },
  { key = "tesco",             category = "Jedlo/potraviny" },
  { key = "billa",             category = "Jedlo/potraviny" },
  { key = "mcdonalds",         category = "Jedlo/reštaurácia" },
  { key = "burger king",       category = "Jedlo/reštaurácia" },
  { key = "kfc",               category = "Jedlo/reštaurácia" },
  { key = "wolt",              category = "Jedlo/objednávky" },
  { key = "lieferando",        category = "Jedlo/objednávky" },
  { key = "bolt",              category = "Jedlo/objednávky" },
  { key = "shell",             category = "Auto/doprava/tankovanie" },
  { key = "aral",              category = "Auto/doprava/tankovanie" },
  { key = "omv",               category = "Auto/doprava/tankovanie" },
  { key = "slovnaft",          category = "Auto/doprava/tankovanie" },
  { key = "esso",              category = "Auto/doprava/tankovanie" },
  { key = "netflix",           category = "Predplatné/Netflix" },
  { key = "hbo",               category = "Predplatné/Max HBO" },
  { key = "voyo",              category = "Predplatné/Voyo" },
  { key = "markiza",           category = "Predplatné/Voyo" },
  { key = "youtube",           category = "Predplatné/YouTube" },
  { key = "apple com bill",    category = "Predplatné/Apple" },
  { key = "itunes",            category = "Predplatné/Apple" },
  { key = "spotify",           category = "Predplatné/Apple" },
  { key = "amazon",            category = "Nákupy/obchod" },
  { key = "action",            category = "Nákupy/domácnosť" },
  { key = "bauhaus",           category = "Nákupy/domácnosť" },
  { key = "ikea",              category = "Nákupy/domácnosť" },
  { key = "douglas",           category = "Nákupy/drogéria" },
  { key = "dm",                category = "Nákupy/drogéria" },
  { key = "rossmann",          category = "Nákupy/drogéria" },
  { key = "apotheke",          category = "Zdravie/lekáreň" },
  { key = "lekaren",           category = "Zdravie/lekáreň" },
  { key = "xtb",               category = "Investovanie/XTB" },
  { key = "finax",             category = "Investovanie/Finax" },
  { key = "binance",           category = "Investovanie/Binance" },
  { key = "socialna poistovna", category = "Odvody a poistenie/sociálka" },
  { key = "o2",                category = "Internet/telefón/mobil" },
  { key = "telekom",           category = "Internet/telefón/mobil" },
  { key = "orange",            category = "Internet/telefón/mobil" },
  { key = "poplatok",          category = "Poplatky/banka" },
]
